import type { Metadata } from "next";
import { Inter, Stick } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import StickyNav from "@/component/StickyNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <StickyNav/>
        {children}
      </body>
    </html>
  );
}
